# 配置文件内容
[supervisord]
# 容器必须前台运行
nodaemon=true
# 关闭supervisor自身日志（容器直接 stdout）
logfile=/dev/null
# 不滚动、不写文件
logfile_maxbytes=0
# 只打错误，别用info/debug
loglevel=error
pidfile=/tmp/supervisord.pid
minfds=1024
minprocs=200
# 降低心跳轮询间隔，减少CPU，默认3秒，够用就别改更小
poll_interval=3
# 关闭不必要的事件系统
nocleanup=false
# 过滤ANSI颜色，减少处理开销
strip_ansi=true
# 显式指定root，消除降权警告;若想非root运行，先创建用户（见方案2），再改这里为普通用户名
user=root

# 关闭不必要的 HTTP 管理（非常有用）如果你不需要在容器里用 web 界面 / XML-RPC 控制，直接关掉，注释掉或删掉整个这段
# [inet_http_server]
# port=127.0.0.1:9001
# username=user
# password=123

# 如果你不用API控制和使用supervisorctl，也可以注释（但一般保留也不怎么占资源）
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

# 如果你不用 supervisorctl / 外部控制，直接注释掉整个段
[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700
# 认证用户名
# username=admin
# 认证密码（生产建议用环境变量）
# password=your_strong_password

# 不用就注释
[supervisorctl]
serverurl=unix:///var/run/supervisor.sock
# username=admin
# password=your_strong_password

[program:sshd]
command=/usr/sbin/sshd -D
autostart=true
# 异常退出才重启，别用true
# 当程序exit的时候，这个program不会自动重启,默认unexpected
# 设置子进程挂掉后自动重启的情况，有三个选项，false,unexpected和true。如果为false的时候，无论什么情况下，都不会被重新启动，如果为unexpected，只有当进程的退出码不在下面的exitcodes里面定义的
autorestart=unexpected
startretries=3
# 认为启动成功的秒数
startsecs=2
# 日志全部走 stdout，禁用文件日志
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
# 关闭无用功能
stopwaitsecs=5
# 一并杀子进程，避免僵尸
killasgroup=true
# 非root运行，更安全也略轻
# user=appuser


[program:webssh]
command=/root/bin/webssh --delay=10 --encoding=utf-8 --fbidhttp=False --maxconn=20 --origin='*' --policy=warning --redirect=False --timeout=10 --port=8888 --debug --xsrf=False --xheaders --wpintvl=1
autostart=true
autorestart=unexpected
startretries=3
startsecs=2
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopwaitsecs=5
killasgroup=true

[program:dufs]
command=/root/bin/dufs -p 5000 --allow-upload -a club:123456@/:rw
autostart=true
autorestart=unexpected
startretries=3
startsecs=2
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopwaitsecs=5
killasgroup=true
